pipeline{
    agent{
        label 'AGENT-1'
    }
    
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    parameters{
        choice(name: 'ACTION', choices: ['apply','destroy'], description: 'select action')
    }

    stages{
        stage('init and plan'){
            steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                        cd 10-sg
                        terraform init -reconfigure
                        terraform plan -out=tfplan
                    """
                }
            }
        }

        // terraform apply or destroy 
        stage('Apply or Destroy'){
            input {
                message "should we continue to ${params.ACTION}"
                ok "yes. we should."
            }
            steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                        cd 10-sg
                        if [ "${params.ACTION}" == "apply" ]
                        then
                            terraform apply -auto-approve
                        elif [ "${params.ACTION}" == "destroy" ]
                        then
                            terraform destroy -auto-approve
                        fi
                    """
                }
            }
        }
    }
}