pipeline{
    agent{
        label 'AGENT-1'
    }
    
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansicolor('xterm')
    }

    parameters{
        choice(name: 'ACTION', choices: ['apply','destroy'], description: 'select action')
    }

    stages{
        stage('init and plan'){
            withAWS(region: 'us-east-1', credentials: 'aws-auth'){
                sh """
                    cd 10-sg
                    terraform init -reconfigure
                    terraform plan -out=tfplan
                """
            }

        }
    }
}